# Generated by Django 5.2.6 on 2025-10-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_book_cover_book_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(help_text='The rating that the reviewer has given.'),
        ),
    ]
