# Generated by Django 5.2.6 on 2025-09-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_publisher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(help_text='The name of the publisher.', max_length=50),
        ),
    ]
