# Generated by Django 5.2.6 on 2025-09-24 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_book_publisher_bookcontributor_book_contributors_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='first_name',
            new_name='first_names',
        ),
    ]
