# Generated by Django 5.2.6 on 2025-09-24 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_rename_first_name_contributor_first_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='first_names',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='contributor',
            old_name='last_name',
            new_name='last_names',
        ),
    ]
