# Generated by Django 5.2.6 on 2025-09-25 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_rename_first_name_contributor_first_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcontributor',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reviews.contributor'),
        ),
    ]
